name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4.1'
    - name: make
      run: make all
