name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
           xcode-version: '13.4.1'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          xcodebuild clean build -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
	  mkdir build/Debug-iphoneos/Payload
          mv build/Debug-iphoneos/p0laris.app build/Debug-iphoneos/Payload/p0laris.app
	  cd build/Debug-iphoneos/; zip -r p0laris-Debug.ipa Payload; mv p0laris*.ipa ../../
          xcodebuild clean build -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          mkdir build/Release-iphoneos/Payload
          mv build/Release-iphoneos/p0laris.app build/Release-iphoneos/Payload/p0laris.app
          cd build/Release-iphoneos/; zip -r p0laris-Release.ipa Payload; mv p0laris*.ipa ../../
